# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 20:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1900)),
                ('model', models.CharField(default='', max_length=100)),
                ('engine_displacement', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('engine_number_of_cylinders', models.IntegerField(default=0)),
                ('horsepower', models.IntegerField(blank=True, default=0)),
                ('torque', models.IntegerField(blank=True, default=0)),
                ('zero_to_sixty_acceleration_time', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='car_sort_app.CarMake')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('review_text', models.TextField(default='')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='car_sort_app.CarModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
    ]
