# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_sort_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='engine_displacement',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='zero_to_sixty_acceleration_time',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
